
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #include <libide-core.h>

            G_BEGIN_DECLS

/* enumerations from "ide-vcs-config.h" */

_IDE_EXTERN
GType ide_vcs_config_type_get_type (void);
#define IDE_TYPE_VCS_CONFIG_TYPE (ide_vcs_config_type_get_type())

/* enumerations from "ide-vcs-file-info.h" */

_IDE_EXTERN
GType ide_vcs_file_status_get_type (void);
#define IDE_TYPE_VCS_FILE_STATUS (ide_vcs_file_status_get_type())

G_END_DECLS

/* Generated data ends here */

