
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #include <libide-core.h>

            G_BEGIN_DECLS

/* enumerations from "ide-file-transfer.h" */

_IDE_EXTERN
GType ide_file_transfer_flags_get_type (void);
#define IDE_TYPE_FILE_TRANSFER_FLAGS (ide_file_transfer_flags_get_type())

G_END_DECLS

/* Generated data ends here */

