
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #include <libide-core.h>

            G_BEGIN_DECLS

G_END_DECLS

/* Generated data ends here */

