
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #include <libide-core.h>

            G_BEGIN_DECLS

/* enumerations from "ide-tree-node.h" */

_IDE_EXTERN
GType ide_tree_node_visit_get_type (void);
#define IDE_TYPE_TREE_NODE_VISIT (ide_tree_node_visit_get_type())

_IDE_EXTERN
GType ide_tree_node_flags_get_type (void);
#define IDE_TYPE_TREE_NODE_FLAGS (ide_tree_node_flags_get_type())

G_END_DECLS

/* Generated data ends here */

