
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

            #include <glib-object.h>
            #include <libide-core.h>

            G_BEGIN_DECLS

/* enumerations from "ide-buffer-manager.h" */

_IDE_EXTERN
GType ide_buffer_open_flags_get_type (void);
#define IDE_TYPE_BUFFER_OPEN_FLAGS (ide_buffer_open_flags_get_type())

/* enumerations from "ide-buffer.h" */

_IDE_EXTERN
GType ide_buffer_state_get_type (void);
#define IDE_TYPE_BUFFER_STATE (ide_buffer_state_get_type())

/* enumerations from "ide-diagnostic.h" */

_IDE_EXTERN
GType ide_diagnostic_severity_get_type (void);
#define IDE_TYPE_DIAGNOSTIC_SEVERITY (ide_diagnostic_severity_get_type())

/* enumerations from "ide-indent-style.h" */

_IDE_EXTERN
GType ide_indent_style_get_type (void);
#define IDE_TYPE_INDENT_STYLE (ide_indent_style_get_type())

/* enumerations from "ide-spaces-style.h" */

_IDE_EXTERN
GType ide_spaces_style_get_type (void);
#define IDE_TYPE_SPACES_STYLE (ide_spaces_style_get_type())

/* enumerations from "ide-symbol.h" */

_IDE_EXTERN
GType ide_symbol_kind_get_type (void);
#define IDE_TYPE_SYMBOL_KIND (ide_symbol_kind_get_type())

_IDE_EXTERN
GType ide_symbol_flags_get_type (void);
#define IDE_TYPE_SYMBOL_FLAGS (ide_symbol_flags_get_type())

G_END_DECLS

/* Generated data ends here */

